### ISSUE TITLE
Pages without a meta description: Reduce extra space at the bottom of widget

### ISSUE THREAD

**Issue by nitsan-technologies** [TYPO3-Initiatives/dashboard#116]
# Bug Report

## Prerequisites

* [ ] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v10
* [ ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3-Initiatives%2FDashboard) to see if your bug or feature is already reported?

## Description

There is a lot of space at the bottom of few widgets if data/records are less. Check these widgets: Pages without a meta description, Last 5 logins

## Steps to Reproduce

1. Go to Dashboard module.
2. Click on "+" button and add following widgets: Pages without a meta description, Last 5 logins
3. Make sure that Pages without a meta description widget has few (<5) records.

**Expected behavior:** We should reduce the space at bottom of widgets which can be used for other widgets.

**Actual behavior:** Currently, empty space is displayed at bottom.

Check this screenshot:

![widget-bottom-space](https://user-images.githubusercontent.com/2622317/73263575-de909900-41f6-11ea-893d-fbcd164290f7.png)
