### ISSUE TITLE
Pages without a meta description crashed if you have no tree/pages

### ISSUE THREAD

**Issue by sfsmfc** [TYPO3-Initiatives/dashboard#79]
# Bug Report
If you add the dashboard "Pages without a meta description", you get a http 500 error, even then you have no pages/no tree.

## Prerequisites

* [x] Can you reproduce the problem on TYPO3 v9.5 LTS
* [ ] Can you reproduce the problem on TYPO3 v10
* [ ] Did you [perform a cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3ATYPO3-Initiatives%2FDashboard) to see if your bug or feature is already reported?

## Steps to Reproduce

1. Use a fresh TYPo3 9 LTS version
2. Add a "Pages without a meta description" widget.

**Comment by sfsmfc** [comment]
I issue is in version 1.0.0 and is already fixed in master.
